version: '1'

services:
  web:
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=${AUTH_URL}
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
            
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db